var wms_layers = [];


        var lyr_ESRIGraylight_0 = new ol.layer.Tile({
            'title': 'ESRI Gray (light)',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}'
            })
        });
var format_CES3DACs_1 = new ol.format.GeoJSON();
var features_CES3DACs_1 = format_CES3DACs_1.readFeatures(json_CES3DACs_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES3DACs_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES3DACs_1.addFeatures(features_CES3DACs_1);
var lyr_CES3DACs_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES3DACs_1, 
                style: style_CES3DACs_1,
                popuplayertitle: 'CES3DACs',
                interactive: true,
                title: '<img src="styles/legend/CES3DACs_1.png" /> CES3DACs'
            });
var format_CES4DACs_2 = new ol.format.GeoJSON();
var features_CES4DACs_2 = format_CES4DACs_2.readFeatures(json_CES4DACs_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES4DACs_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES4DACs_2.addFeatures(features_CES4DACs_2);
var lyr_CES4DACs_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES4DACs_2, 
                style: style_CES4DACs_2,
                popuplayertitle: 'CES4DACs',
                interactive: true,
                title: '<img src="styles/legend/CES4DACs_2.png" /> CES4DACs'
            });
var format_CES5DraftDACs_3 = new ol.format.GeoJSON();
var features_CES5DraftDACs_3 = format_CES5DraftDACs_3.readFeatures(json_CES5DraftDACs_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES5DraftDACs_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES5DraftDACs_3.addFeatures(features_CES5DraftDACs_3);
var lyr_CES5DraftDACs_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES5DraftDACs_3, 
                style: style_CES5DraftDACs_3,
                popuplayertitle: 'CES5 Draft DACs',
                interactive: true,
                title: '<img src="styles/legend/CES5DraftDACs_3.png" /> CES5 Draft DACs'
            });
var format_CES5FinalDACs_4 = new ol.format.GeoJSON();
var features_CES5FinalDACs_4 = format_CES5FinalDACs_4.readFeatures(json_CES5FinalDACs_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES5FinalDACs_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES5FinalDACs_4.addFeatures(features_CES5FinalDACs_4);
var lyr_CES5FinalDACs_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES5FinalDACs_4, 
                style: style_CES5FinalDACs_4,
                popuplayertitle: 'CES5 Final DACs',
                interactive: true,
                title: '<img src="styles/legend/CES5FinalDACs_4.png" /> CES5 Final DACs'
            });
var format_AssemblyDistrict_5 = new ol.format.GeoJSON();
var features_AssemblyDistrict_5 = format_AssemblyDistrict_5.readFeatures(json_AssemblyDistrict_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_AssemblyDistrict_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_AssemblyDistrict_5.addFeatures(features_AssemblyDistrict_5);
var lyr_AssemblyDistrict_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_AssemblyDistrict_5, 
                style: style_AssemblyDistrict_5,
                popuplayertitle: 'Assembly District',
                interactive: true,
                title: '<img src="styles/legend/AssemblyDistrict_5.png" /> Assembly District'
            });
var format_SenateDistrict_6 = new ol.format.GeoJSON();
var features_SenateDistrict_6 = format_SenateDistrict_6.readFeatures(json_SenateDistrict_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_SenateDistrict_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SenateDistrict_6.addFeatures(features_SenateDistrict_6);
var lyr_SenateDistrict_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SenateDistrict_6, 
                style: style_SenateDistrict_6,
                popuplayertitle: 'Senate District',
                interactive: true,
                title: '<img src="styles/legend/SenateDistrict_6.png" /> Senate District'
            });

lyr_ESRIGraylight_0.setVisible(true);lyr_CES3DACs_1.setVisible(true);lyr_CES4DACs_2.setVisible(true);lyr_CES5DraftDACs_3.setVisible(true);lyr_CES5FinalDACs_4.setVisible(true);lyr_AssemblyDistrict_5.setVisible(true);lyr_SenateDistrict_6.setVisible(true);
var layersList = [lyr_ESRIGraylight_0,lyr_CES3DACs_1,lyr_CES4DACs_2,lyr_CES5DraftDACs_3,lyr_CES5FinalDACs_4,lyr_AssemblyDistrict_5,lyr_SenateDistrict_6];
lyr_CES3DACs_1.set('fieldAliases', {'tract': 'tract', 'pop2010': 'pop2010', 'California': 'California', 'ZIP': 'ZIP', 'City': 'City', 'Longitude': 'Longitude', 'Latitude': 'Latitude', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'drink': 'drink', 'drinkP': 'drinkP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatsP': 'gwthreatsP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'swis': 'swis', 'swisP': 'swisP', 'Pollution': 'Pollution', 'PollutionS': 'PollutionS', 'PollutionP': 'PollutionP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'edu': 'edu', 'eduP': 'eduP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'PopChar': 'PopChar', 'PopCharSco': 'PopCharSco', 'PopCharP': 'PopCharP', 'Children_u': 'Children_u', 'Pop_11_64_': 'Pop_11_64_', 'Elderly_ov': 'Elderly_ov', 'Hispanic_p': 'Hispanic_p', 'White_pct': 'White_pct', 'African_Am': 'African_Am', 'Native_Ame': 'Native_Ame', 'Asian_Amer': 'Asian_Amer', 'Other_pct': 'Other_pct', 'OBJECTID_1': 'OBJECTID_1', 'CIdecile': 'CIdecile', 'CIvigintil': 'CIvigintil', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'CES2018_Rn': 'CES2018_Rn', });
lyr_CES4DACs_2.set('fieldAliases', {'Tract': 'Tract', 'ZIP': 'ZIP', 'County': 'County', 'ApproxLoc': 'ApproxLoc', 'TotPop19': 'TotPop19', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'Ozone': 'Ozone', 'OzoneP': 'OzoneP', 'PM2_5': 'PM2_5', 'PM2_5_P': 'PM2_5_P', 'DieselPM': 'DieselPM', 'DieselPM_P': 'DieselPM_P', 'Pesticide': 'Pesticide', 'PesticideP': 'PesticideP', 'Tox_Rel': 'Tox_Rel', 'Tox_Rel_P': 'Tox_Rel_P', 'Traffic': 'Traffic', 'TrafficP': 'TrafficP', 'DrinkWat': 'DrinkWat', 'DrinkWatP': 'DrinkWatP', 'Lead': 'Lead', 'Lead_P': 'Lead_P', 'Cleanup': 'Cleanup', 'CleanupP': 'CleanupP', 'GWThreat': 'GWThreat', 'GWThreatP': 'GWThreatP', 'HazWaste': 'HazWaste', 'HazWasteP': 'HazWasteP', 'ImpWatBod': 'ImpWatBod', 'ImpWatBodP': 'ImpWatBodP', 'SolWaste': 'SolWaste', 'SolWasteP': 'SolWasteP', 'PollBurd': 'PollBurd', 'PolBurdSc': 'PolBurdSc', 'PolBurdP': 'PolBurdP', 'Asthma': 'Asthma', 'AsthmaP': 'AsthmaP', 'LowBirtWt': 'LowBirtWt', 'LowBirWP': 'LowBirWP', 'Cardiovas': 'Cardiovas', 'CardiovasP': 'CardiovasP', 'Educatn': 'Educatn', 'EducatP': 'EducatP', 'Ling_Isol': 'Ling_Isol', 'Ling_IsolP': 'Ling_IsolP', 'Poverty': 'Poverty', 'PovertyP': 'PovertyP', 'Unempl': 'Unempl', 'UnemplP': 'UnemplP', 'HousBurd': 'HousBurd', 'HousBurdP': 'HousBurdP', 'PopChar': 'PopChar', 'PopCharSc': 'PopCharSc', 'PopCharP': 'PopCharP', 'Child_10': 'Child_10', 'Pop_10_64': 'Pop_10_64', 'Elderly65': 'Elderly65', 'Hispanic': 'Hispanic', 'White': 'White', 'AfricanAm': 'AfricanAm', 'NativeAm': 'NativeAm', 'OtherMult': 'OtherMult', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'AAPI': 'AAPI', });
lyr_CES5DraftDACs_3.set('fieldAliases', {'tract': 'tract', 'ZIP': 'ZIP', 'apx_loc': 'apx_loc', 'county': 'county', 'region': 'region', 'pop': 'pop', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'lead': 'lead', 'leadP': 'leadP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'drink': 'drink', 'drinkP': 'drinkP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatP': 'gwthreatP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'SmATS': 'SmATS', 'SmATSP': 'SmATSP', 'swis': 'swis', 'swisP': 'swisP', 'pollutn': 'pollutn', 'pltn_scr': 'pltn_scr', 'pollutnP': 'pollutnP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'diabetes': 'diabetes', 'diabetesP': 'diabetesP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'edu': 'edu', 'eduP': 'eduP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'PopChar': 'PopChar', 'PopCharScr': 'PopCharScr', 'PopCharP': 'PopCharP', 'PopUnd_10': 'PopUnd_10', 'Pop10_64': 'Pop10_64', 'popovr_65': 'popovr_65', 'whitepct': 'whitepct', 'hisppct': 'hisppct', 'blackpct': 'blackpct', 'nativeampc': 'nativeampc', 'asianpct': 'asianpct', 'otherpct': 'otherpct', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_CES5FinalDACs_4.set('fieldAliases', {'tract': 'tract', 'zipcode': 'zipcode', 'approx_loc': 'approx_loc', 'county': 'county', 'region': 'region', 'ACS2024Pop': 'ACS2024Pop', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'drink': 'drink', 'drinkP': 'drinkP', 'lead': 'lead', 'leadP': 'leadP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatsP': 'gwthreatsP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'swis': 'swis', 'swisP': 'swisP', 'SmATS': 'SmATS', 'SmATSP': 'SmATSP', 'Pollution': 'Pollution', 'PollutionS': 'PollutionS', 'PollutionP': 'PollutionP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'diabetes': 'diabetes', 'diabetesP': 'diabetesP', 'edu': 'edu', 'eduP': 'eduP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'PopChar': 'PopChar', 'PopCharSco': 'PopCharSco', 'PopCharP': 'PopCharP', 'pop_und10': 'pop_und10', 'pop_10_64': 'pop_10_64', 'pop_ov64': 'pop_ov64', 'hisp': 'hisp', 'white': 'white', 'black': 'black', 'amind': 'amind', 'asian': 'asian', 'pacisl': 'pacisl', 'othmult': 'othmult', });
lyr_AssemblyDistrict_5.set('fieldAliases', {'ID': 'ID', 'AREA': 'AREA', 'DISTRICT': 'DISTRICT', 'MEMBERS': 'MEMBERS', 'LOCKED': 'LOCKED', 'NAME': 'NAME', 'POPULATION': 'POPULATION', 'CVAP_19': 'CVAP_19', 'HSP_CVAP_1': 'HSP_CVAP_1', 'DOJ_NH_BLK': 'DOJ_NH_BLK', 'DOJ_NH_ASN': 'DOJ_NH_ASN', 'NH_WHT_CVA': 'NH_WHT_CVA', 'IDEAL_VALU': 'IDEAL_VALU', 'DEVIATION': 'DEVIATION', 'F_DEVIATIO': 'F_DEVIATIO', 'F_CVAP_19': 'F_CVAP_19', 'F_HSP_CVAP': 'F_HSP_CVAP', 'F_DOJ_NH_B': 'F_DOJ_NH_B', 'F_DOJ_NH_A': 'F_DOJ_NH_A', 'F_NH_WHT_C': 'F_NH_WHT_C', 'DISTRICT_N': 'DISTRICT_N', 'DISTRICT_L': 'DISTRICT_L', });
lyr_SenateDistrict_6.set('fieldAliases', {'ID': 'ID', 'AREA': 'AREA', 'DISTRICT': 'DISTRICT', 'MEMBERS': 'MEMBERS', 'LOCKED': 'LOCKED', 'NAME': 'NAME', 'POPULATION': 'POPULATION', 'CVAP_19': 'CVAP_19', 'HSP_CVAP_1': 'HSP_CVAP_1', 'DOJ_NH_IND': 'DOJ_NH_IND', 'DOJ_NH_BLK': 'DOJ_NH_BLK', 'DOJ_NH_ASN': 'DOJ_NH_ASN', 'NH_WHT_CVA': 'NH_WHT_CVA', 'IDEAL_VALU': 'IDEAL_VALU', 'DEVIATION': 'DEVIATION', 'F_DEVIATIO': 'F_DEVIATIO', 'F_CVAP_19': 'F_CVAP_19', 'F_HSP_CVAP': 'F_HSP_CVAP', 'F_DOJ_NH_I': 'F_DOJ_NH_I', 'F_DOJ_NH_B': 'F_DOJ_NH_B', 'F_DOJ_NH_A': 'F_DOJ_NH_A', 'F_NH_WHT_C': 'F_NH_WHT_C', 'DISTRICT_L': 'DISTRICT_L', 'MULTIPLE_F': 'MULTIPLE_F', });
lyr_CES3DACs_1.set('fieldImages', {'tract': 'TextEdit', 'pop2010': 'TextEdit', 'California': 'TextEdit', 'ZIP': 'TextEdit', 'City': 'TextEdit', 'Longitude': 'TextEdit', 'Latitude': 'TextEdit', 'CIscore': 'TextEdit', 'CIscoreP': 'TextEdit', 'ozone': 'TextEdit', 'ozoneP': 'TextEdit', 'pm': 'TextEdit', 'pmP': 'TextEdit', 'diesel': 'TextEdit', 'dieselP': 'TextEdit', 'drink': 'TextEdit', 'drinkP': 'TextEdit', 'pest': 'TextEdit', 'pestP': 'TextEdit', 'RSEIhaz': 'TextEdit', 'RSEIhazP': 'TextEdit', 'traffic': 'TextEdit', 'trafficP': 'TextEdit', 'cleanups': 'TextEdit', 'cleanupsP': 'TextEdit', 'gwthreats': 'TextEdit', 'gwthreatsP': 'TextEdit', 'haz': 'TextEdit', 'hazP': 'TextEdit', 'iwb': 'TextEdit', 'iwbP': 'TextEdit', 'swis': 'TextEdit', 'swisP': 'TextEdit', 'Pollution': 'TextEdit', 'PollutionS': 'TextEdit', 'PollutionP': 'TextEdit', 'asthma': 'TextEdit', 'asthmaP': 'TextEdit', 'lbw': 'TextEdit', 'lbwP': 'TextEdit', 'cvd': 'TextEdit', 'cvdP': 'TextEdit', 'edu': 'TextEdit', 'eduP': 'TextEdit', 'ling': 'TextEdit', 'lingP': 'TextEdit', 'pov': 'TextEdit', 'povP': 'TextEdit', 'unemp': 'TextEdit', 'unempP': 'TextEdit', 'housingB': 'TextEdit', 'housingBP': 'TextEdit', 'PopChar': 'TextEdit', 'PopCharSco': 'TextEdit', 'PopCharP': 'TextEdit', 'Children_u': 'TextEdit', 'Pop_11_64_': 'TextEdit', 'Elderly_ov': 'TextEdit', 'Hispanic_p': 'TextEdit', 'White_pct': 'TextEdit', 'African_Am': 'TextEdit', 'Native_Ame': 'TextEdit', 'Asian_Amer': 'TextEdit', 'Other_pct': 'TextEdit', 'OBJECTID_1': 'TextEdit', 'CIdecile': 'TextEdit', 'CIvigintil': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', 'CES2018_Rn': 'TextEdit', });
lyr_CES4DACs_2.set('fieldImages', {'Tract': 'TextEdit', 'ZIP': 'TextEdit', 'County': 'TextEdit', 'ApproxLoc': 'TextEdit', 'TotPop19': 'TextEdit', 'CIscore': 'TextEdit', 'CIscoreP': 'TextEdit', 'Ozone': 'TextEdit', 'OzoneP': 'TextEdit', 'PM2_5': 'TextEdit', 'PM2_5_P': 'TextEdit', 'DieselPM': 'TextEdit', 'DieselPM_P': 'TextEdit', 'Pesticide': 'TextEdit', 'PesticideP': 'TextEdit', 'Tox_Rel': 'TextEdit', 'Tox_Rel_P': 'TextEdit', 'Traffic': 'TextEdit', 'TrafficP': 'TextEdit', 'DrinkWat': 'TextEdit', 'DrinkWatP': 'TextEdit', 'Lead': 'TextEdit', 'Lead_P': 'TextEdit', 'Cleanup': 'TextEdit', 'CleanupP': 'TextEdit', 'GWThreat': 'TextEdit', 'GWThreatP': 'TextEdit', 'HazWaste': 'TextEdit', 'HazWasteP': 'TextEdit', 'ImpWatBod': 'TextEdit', 'ImpWatBodP': 'TextEdit', 'SolWaste': 'TextEdit', 'SolWasteP': 'TextEdit', 'PollBurd': 'TextEdit', 'PolBurdSc': 'TextEdit', 'PolBurdP': 'TextEdit', 'Asthma': 'TextEdit', 'AsthmaP': 'TextEdit', 'LowBirtWt': 'TextEdit', 'LowBirWP': 'TextEdit', 'Cardiovas': 'TextEdit', 'CardiovasP': 'TextEdit', 'Educatn': 'TextEdit', 'EducatP': 'TextEdit', 'Ling_Isol': 'TextEdit', 'Ling_IsolP': 'TextEdit', 'Poverty': 'TextEdit', 'PovertyP': 'TextEdit', 'Unempl': 'TextEdit', 'UnemplP': 'TextEdit', 'HousBurd': 'TextEdit', 'HousBurdP': 'TextEdit', 'PopChar': 'TextEdit', 'PopCharSc': 'TextEdit', 'PopCharP': 'TextEdit', 'Child_10': 'TextEdit', 'Pop_10_64': 'TextEdit', 'Elderly65': 'TextEdit', 'Hispanic': 'TextEdit', 'White': 'TextEdit', 'AfricanAm': 'TextEdit', 'NativeAm': 'TextEdit', 'OtherMult': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', 'AAPI': 'TextEdit', });
lyr_CES5DraftDACs_3.set('fieldImages', {'tract': 'TextEdit', 'ZIP': 'TextEdit', 'apx_loc': 'TextEdit', 'county': 'TextEdit', 'region': 'TextEdit', 'pop': 'TextEdit', 'CIscore': 'TextEdit', 'CIscoreP': 'TextEdit', 'ozone': 'TextEdit', 'ozoneP': 'TextEdit', 'pm': 'TextEdit', 'pmP': 'TextEdit', 'lead': 'TextEdit', 'leadP': 'TextEdit', 'diesel': 'TextEdit', 'dieselP': 'TextEdit', 'drink': 'TextEdit', 'drinkP': 'TextEdit', 'pest': 'TextEdit', 'pestP': 'TextEdit', 'RSEIhaz': 'TextEdit', 'RSEIhazP': 'TextEdit', 'traffic': 'TextEdit', 'trafficP': 'TextEdit', 'cleanups': 'TextEdit', 'cleanupsP': 'TextEdit', 'gwthreats': 'TextEdit', 'gwthreatP': 'TextEdit', 'haz': 'TextEdit', 'hazP': 'TextEdit', 'iwb': 'TextEdit', 'iwbP': 'TextEdit', 'SmATS': 'TextEdit', 'SmATSP': 'TextEdit', 'swis': 'TextEdit', 'swisP': 'TextEdit', 'pollutn': 'TextEdit', 'pltn_scr': 'TextEdit', 'pollutnP': 'TextEdit', 'asthma': 'TextEdit', 'asthmaP': 'TextEdit', 'cvd': 'TextEdit', 'cvdP': 'TextEdit', 'diabetes': 'TextEdit', 'diabetesP': 'TextEdit', 'lbw': 'TextEdit', 'lbwP': 'TextEdit', 'edu': 'TextEdit', 'eduP': 'TextEdit', 'housingB': 'TextEdit', 'housingBP': 'TextEdit', 'ling': 'TextEdit', 'lingP': 'TextEdit', 'pov': 'TextEdit', 'povP': 'TextEdit', 'unemp': 'TextEdit', 'unempP': 'TextEdit', 'PopChar': 'TextEdit', 'PopCharScr': 'TextEdit', 'PopCharP': 'TextEdit', 'PopUnd_10': 'TextEdit', 'Pop10_64': 'TextEdit', 'popovr_65': 'TextEdit', 'whitepct': 'TextEdit', 'hisppct': 'TextEdit', 'blackpct': 'TextEdit', 'nativeampc': 'TextEdit', 'asianpct': 'TextEdit', 'otherpct': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', });
lyr_CES5FinalDACs_4.set('fieldImages', {'tract': 'TextEdit', 'zipcode': 'Range', 'approx_loc': 'TextEdit', 'county': 'TextEdit', 'region': 'TextEdit', 'ACS2024Pop': 'TextEdit', 'CIscore': 'TextEdit', 'CIscoreP': 'TextEdit', 'ozone': 'TextEdit', 'ozoneP': 'TextEdit', 'pm': 'TextEdit', 'pmP': 'TextEdit', 'diesel': 'TextEdit', 'dieselP': 'TextEdit', 'pest': 'TextEdit', 'pestP': 'TextEdit', 'RSEIhaz': 'TextEdit', 'RSEIhazP': 'TextEdit', 'traffic': 'TextEdit', 'trafficP': 'TextEdit', 'drink': 'TextEdit', 'drinkP': 'TextEdit', 'lead': 'TextEdit', 'leadP': 'TextEdit', 'cleanups': 'TextEdit', 'cleanupsP': 'TextEdit', 'gwthreats': 'TextEdit', 'gwthreatsP': 'TextEdit', 'haz': 'TextEdit', 'hazP': 'TextEdit', 'iwb': 'TextEdit', 'iwbP': 'TextEdit', 'swis': 'TextEdit', 'swisP': 'TextEdit', 'SmATS': 'TextEdit', 'SmATSP': 'TextEdit', 'Pollution': 'TextEdit', 'PollutionS': 'TextEdit', 'PollutionP': 'TextEdit', 'asthma': 'TextEdit', 'asthmaP': 'TextEdit', 'lbw': 'TextEdit', 'lbwP': 'TextEdit', 'cvd': 'TextEdit', 'cvdP': 'TextEdit', 'diabetes': 'TextEdit', 'diabetesP': 'TextEdit', 'edu': 'TextEdit', 'eduP': 'TextEdit', 'ling': 'TextEdit', 'lingP': 'TextEdit', 'pov': 'TextEdit', 'povP': 'TextEdit', 'unemp': 'TextEdit', 'unempP': 'TextEdit', 'housingB': 'TextEdit', 'housingBP': 'TextEdit', 'PopChar': 'TextEdit', 'PopCharSco': 'TextEdit', 'PopCharP': 'TextEdit', 'pop_und10': 'TextEdit', 'pop_10_64': 'TextEdit', 'pop_ov64': 'TextEdit', 'hisp': 'TextEdit', 'white': 'TextEdit', 'black': 'TextEdit', 'amind': 'TextEdit', 'asian': 'TextEdit', 'pacisl': 'TextEdit', 'othmult': 'TextEdit', });
lyr_AssemblyDistrict_5.set('fieldImages', {'ID': 'TextEdit', 'AREA': 'TextEdit', 'DISTRICT': 'TextEdit', 'MEMBERS': 'TextEdit', 'LOCKED': 'TextEdit', 'NAME': 'TextEdit', 'POPULATION': 'TextEdit', 'CVAP_19': 'TextEdit', 'HSP_CVAP_1': 'TextEdit', 'DOJ_NH_BLK': 'TextEdit', 'DOJ_NH_ASN': 'TextEdit', 'NH_WHT_CVA': 'TextEdit', 'IDEAL_VALU': 'TextEdit', 'DEVIATION': 'TextEdit', 'F_DEVIATIO': 'TextEdit', 'F_CVAP_19': 'TextEdit', 'F_HSP_CVAP': 'TextEdit', 'F_DOJ_NH_B': 'TextEdit', 'F_DOJ_NH_A': 'TextEdit', 'F_NH_WHT_C': 'TextEdit', 'DISTRICT_N': 'TextEdit', 'DISTRICT_L': 'TextEdit', });
lyr_SenateDistrict_6.set('fieldImages', {'ID': 'TextEdit', 'AREA': 'TextEdit', 'DISTRICT': 'TextEdit', 'MEMBERS': 'TextEdit', 'LOCKED': 'TextEdit', 'NAME': 'TextEdit', 'POPULATION': 'TextEdit', 'CVAP_19': 'TextEdit', 'HSP_CVAP_1': 'TextEdit', 'DOJ_NH_IND': 'TextEdit', 'DOJ_NH_BLK': 'TextEdit', 'DOJ_NH_ASN': 'TextEdit', 'NH_WHT_CVA': 'TextEdit', 'IDEAL_VALU': 'TextEdit', 'DEVIATION': 'TextEdit', 'F_DEVIATIO': 'TextEdit', 'F_CVAP_19': 'TextEdit', 'F_HSP_CVAP': 'TextEdit', 'F_DOJ_NH_I': 'TextEdit', 'F_DOJ_NH_B': 'TextEdit', 'F_DOJ_NH_A': 'TextEdit', 'F_NH_WHT_C': 'TextEdit', 'DISTRICT_L': 'TextEdit', 'MULTIPLE_F': 'TextEdit', });
lyr_CES3DACs_1.set('fieldLabels', {'tract': 'header label - always visible', 'pop2010': 'hidden field', 'California': 'hidden field', 'ZIP': 'hidden field', 'City': 'header label - always visible', 'Longitude': 'hidden field', 'Latitude': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatsP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'Pollution': 'hidden field', 'PollutionS': 'hidden field', 'PollutionP': 'hidden field', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'PopChar': 'hidden field', 'PopCharSco': 'hidden field', 'PopCharP': 'hidden field', 'Children_u': 'hidden field', 'Pop_11_64_': 'hidden field', 'Elderly_ov': 'hidden field', 'Hispanic_p': 'hidden field', 'White_pct': 'hidden field', 'African_Am': 'hidden field', 'Native_Ame': 'hidden field', 'Asian_Amer': 'hidden field', 'Other_pct': 'hidden field', 'OBJECTID_1': 'hidden field', 'CIdecile': 'hidden field', 'CIvigintil': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', 'CES2018_Rn': 'hidden field', });
lyr_CES4DACs_2.set('fieldLabels', {'Tract': 'header label - always visible', 'ZIP': 'hidden field', 'County': 'hidden field', 'ApproxLoc': 'header label - always visible', 'TotPop19': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'Ozone': 'hidden field', 'OzoneP': 'hidden field', 'PM2_5': 'hidden field', 'PM2_5_P': 'hidden field', 'DieselPM': 'hidden field', 'DieselPM_P': 'hidden field', 'Pesticide': 'hidden field', 'PesticideP': 'hidden field', 'Tox_Rel': 'hidden field', 'Tox_Rel_P': 'hidden field', 'Traffic': 'hidden field', 'TrafficP': 'hidden field', 'DrinkWat': 'hidden field', 'DrinkWatP': 'hidden field', 'Lead': 'hidden field', 'Lead_P': 'hidden field', 'Cleanup': 'hidden field', 'CleanupP': 'hidden field', 'GWThreat': 'hidden field', 'GWThreatP': 'hidden field', 'HazWaste': 'hidden field', 'HazWasteP': 'hidden field', 'ImpWatBod': 'hidden field', 'ImpWatBodP': 'hidden field', 'SolWaste': 'hidden field', 'SolWasteP': 'hidden field', 'PollBurd': 'hidden field', 'PolBurdSc': 'hidden field', 'PolBurdP': 'hidden field', 'Asthma': 'hidden field', 'AsthmaP': 'hidden field', 'LowBirtWt': 'hidden field', 'LowBirWP': 'hidden field', 'Cardiovas': 'hidden field', 'CardiovasP': 'hidden field', 'Educatn': 'hidden field', 'EducatP': 'hidden field', 'Ling_Isol': 'hidden field', 'Ling_IsolP': 'hidden field', 'Poverty': 'hidden field', 'PovertyP': 'hidden field', 'Unempl': 'hidden field', 'UnemplP': 'hidden field', 'HousBurd': 'hidden field', 'HousBurdP': 'hidden field', 'PopChar': 'hidden field', 'PopCharSc': 'hidden field', 'PopCharP': 'hidden field', 'Child_10': 'hidden field', 'Pop_10_64': 'hidden field', 'Elderly65': 'hidden field', 'Hispanic': 'hidden field', 'White': 'hidden field', 'AfricanAm': 'hidden field', 'NativeAm': 'hidden field', 'OtherMult': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', 'AAPI': 'hidden field', });
lyr_CES5DraftDACs_3.set('fieldLabels', {'tract': 'header label - always visible', 'ZIP': 'hidden field', 'apx_loc': 'header label - always visible', 'county': 'hidden field', 'region': 'hidden field', 'pop': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'lead': 'hidden field', 'leadP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'SmATS': 'hidden field', 'SmATSP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'pollutn': 'hidden field', 'pltn_scr': 'hidden field', 'pollutnP': 'hidden field', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'diabetes': 'hidden field', 'diabetesP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'PopChar': 'hidden field', 'PopCharScr': 'hidden field', 'PopCharP': 'hidden field', 'PopUnd_10': 'hidden field', 'Pop10_64': 'hidden field', 'popovr_65': 'hidden field', 'whitepct': 'hidden field', 'hisppct': 'hidden field', 'blackpct': 'hidden field', 'nativeampc': 'hidden field', 'asianpct': 'hidden field', 'otherpct': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', });
lyr_CES5FinalDACs_4.set('fieldLabels', {'tract': 'header label - always visible', 'zipcode': 'hidden field', 'approx_loc': 'header label - always visible', 'county': 'hidden field', 'region': 'hidden field', 'ACS2024Pop': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'lead': 'hidden field', 'leadP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatsP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'SmATS': 'hidden field', 'SmATSP': 'hidden field', 'Pollution': 'hidden field', 'PollutionS': 'hidden field', 'PollutionP': 'hidden field', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'diabetes': 'hidden field', 'diabetesP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'PopChar': 'hidden field', 'PopCharSco': 'hidden field', 'PopCharP': 'hidden field', 'pop_und10': 'hidden field', 'pop_10_64': 'hidden field', 'pop_ov64': 'hidden field', 'hisp': 'hidden field', 'white': 'hidden field', 'black': 'hidden field', 'amind': 'hidden field', 'asian': 'hidden field', 'pacisl': 'hidden field', 'othmult': 'hidden field', });
lyr_AssemblyDistrict_5.set('fieldLabels', {'ID': 'no label', 'AREA': 'no label', 'DISTRICT': 'no label', 'MEMBERS': 'no label', 'LOCKED': 'no label', 'NAME': 'no label', 'POPULATION': 'no label', 'CVAP_19': 'no label', 'HSP_CVAP_1': 'no label', 'DOJ_NH_BLK': 'no label', 'DOJ_NH_ASN': 'no label', 'NH_WHT_CVA': 'no label', 'IDEAL_VALU': 'no label', 'DEVIATION': 'no label', 'F_DEVIATIO': 'no label', 'F_CVAP_19': 'no label', 'F_HSP_CVAP': 'no label', 'F_DOJ_NH_B': 'no label', 'F_DOJ_NH_A': 'no label', 'F_NH_WHT_C': 'no label', 'DISTRICT_N': 'no label', 'DISTRICT_L': 'no label', });
lyr_SenateDistrict_6.set('fieldLabels', {'ID': 'no label', 'AREA': 'no label', 'DISTRICT': 'no label', 'MEMBERS': 'no label', 'LOCKED': 'no label', 'NAME': 'no label', 'POPULATION': 'no label', 'CVAP_19': 'no label', 'HSP_CVAP_1': 'no label', 'DOJ_NH_IND': 'no label', 'DOJ_NH_BLK': 'no label', 'DOJ_NH_ASN': 'no label', 'NH_WHT_CVA': 'no label', 'IDEAL_VALU': 'no label', 'DEVIATION': 'no label', 'F_DEVIATIO': 'no label', 'F_CVAP_19': 'no label', 'F_HSP_CVAP': 'no label', 'F_DOJ_NH_I': 'no label', 'F_DOJ_NH_B': 'no label', 'F_DOJ_NH_A': 'no label', 'F_NH_WHT_C': 'no label', 'DISTRICT_L': 'no label', 'MULTIPLE_F': 'no label', });
lyr_SenateDistrict_6.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});