var wms_layers = [];


        var lyr_ESRIGraylight_0 = new ol.layer.Tile({
            'title': 'ESRI Gray (light)',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}'
            })
        });
var format_CES3DACs_1 = new ol.format.GeoJSON();
var features_CES3DACs_1 = format_CES3DACs_1.readFeatures(json_CES3DACs_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES3DACs_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES3DACs_1.addFeatures(features_CES3DACs_1);
var lyr_CES3DACs_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES3DACs_1, 
                style: style_CES3DACs_1,
                popuplayertitle: 'CES3DACs',
                interactive: true,
                title: '<img src="styles/legend/CES3DACs_1.png" /> CES3DACs'
            });
var format_CES4DACs_2 = new ol.format.GeoJSON();
var features_CES4DACs_2 = format_CES4DACs_2.readFeatures(json_CES4DACs_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES4DACs_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES4DACs_2.addFeatures(features_CES4DACs_2);
var lyr_CES4DACs_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES4DACs_2, 
                style: style_CES4DACs_2,
                popuplayertitle: 'CES4DACs',
                interactive: true,
                title: '<img src="styles/legend/CES4DACs_2.png" /> CES4DACs'
            });
var format_CES5DACs40_3 = new ol.format.GeoJSON();
var features_CES5DACs40_3 = format_CES5DACs40_3.readFeatures(json_CES5DACs40_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES5DACs40_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES5DACs40_3.addFeatures(features_CES5DACs40_3);
var lyr_CES5DACs40_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES5DACs40_3, 
                style: style_CES5DACs40_3,
                popuplayertitle: 'CES5 DACs 40%',
                interactive: true,
                title: '<img src="styles/legend/CES5DACs40_3.png" /> CES5 DACs 40%'
            });
var format_CES5DACs30_4 = new ol.format.GeoJSON();
var features_CES5DACs30_4 = format_CES5DACs30_4.readFeatures(json_CES5DACs30_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES5DACs30_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES5DACs30_4.addFeatures(features_CES5DACs30_4);
var lyr_CES5DACs30_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES5DACs30_4, 
                style: style_CES5DACs30_4,
                popuplayertitle: 'CES5 DACs 30%',
                interactive: true,
                title: '<img src="styles/legend/CES5DACs30_4.png" /> CES5 DACs 30%'
            });
var format_CES5MTCSolution_5 = new ol.format.GeoJSON();
var features_CES5MTCSolution_5 = format_CES5MTCSolution_5.readFeatures(json_CES5MTCSolution_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES5MTCSolution_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES5MTCSolution_5.addFeatures(features_CES5MTCSolution_5);
var lyr_CES5MTCSolution_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES5MTCSolution_5, 
                style: style_CES5MTCSolution_5,
                popuplayertitle: 'CES 5 MTC Solution',
                interactive: true,
    title: 'CES 5 MTC Solution<br />\
    <img src="styles/legend/CES5MTCSolution_5_0.png" /> CES 5<br />\
    <img src="styles/legend/CES5MTCSolution_5_1.png" /> Pollution Burden<br />\
    <img src="styles/legend/CES5MTCSolution_5_2.png" /> Population Burden<br />' });
var format_CES5DACs_6 = new ol.format.GeoJSON();
var features_CES5DACs_6 = format_CES5DACs_6.readFeatures(json_CES5DACs_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES5DACs_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CES5DACs_6.addFeatures(features_CES5DACs_6);
var lyr_CES5DACs_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CES5DACs_6, 
                style: style_CES5DACs_6,
                popuplayertitle: 'CES5 DACs',
                interactive: true,
                title: '<img src="styles/legend/CES5DACs_6.png" /> CES5 DACs'
            });

lyr_ESRIGraylight_0.setVisible(true);lyr_CES3DACs_1.setVisible(true);lyr_CES4DACs_2.setVisible(true);lyr_CES5DACs40_3.setVisible(true);lyr_CES5DACs30_4.setVisible(true);lyr_CES5MTCSolution_5.setVisible(true);lyr_CES5DACs_6.setVisible(true);
var layersList = [lyr_ESRIGraylight_0,lyr_CES3DACs_1,lyr_CES4DACs_2,lyr_CES5DACs40_3,lyr_CES5DACs30_4,lyr_CES5MTCSolution_5,lyr_CES5DACs_6];
lyr_CES3DACs_1.set('fieldAliases', {'tract': 'tract', 'pop2010': 'pop2010', 'California': 'California', 'ZIP': 'ZIP', 'City': 'City', 'Longitude': 'Longitude', 'Latitude': 'Latitude', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'drink': 'drink', 'drinkP': 'drinkP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatsP': 'gwthreatsP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'swis': 'swis', 'swisP': 'swisP', 'Pollution': 'Pollution', 'PollutionS': 'PollutionS', 'PollutionP': 'PollutionP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'edu': 'edu', 'eduP': 'eduP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'PopChar': 'PopChar', 'PopCharSco': 'PopCharSco', 'PopCharP': 'PopCharP', 'Children_u': 'Children_u', 'Pop_11_64_': 'Pop_11_64_', 'Elderly_ov': 'Elderly_ov', 'Hispanic_p': 'Hispanic_p', 'White_pct': 'White_pct', 'African_Am': 'African_Am', 'Native_Ame': 'Native_Ame', 'Asian_Amer': 'Asian_Amer', 'Other_pct': 'Other_pct', 'OBJECTID_1': 'OBJECTID_1', 'CIdecile': 'CIdecile', 'CIvigintil': 'CIvigintil', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'CES2018_Rn': 'CES2018_Rn', });
lyr_CES4DACs_2.set('fieldAliases', {'Tract': 'Tract', 'ZIP': 'ZIP', 'County': 'County', 'ApproxLoc': 'ApproxLoc', 'TotPop19': 'TotPop19', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'Ozone': 'Ozone', 'OzoneP': 'OzoneP', 'PM2_5': 'PM2_5', 'PM2_5_P': 'PM2_5_P', 'DieselPM': 'DieselPM', 'DieselPM_P': 'DieselPM_P', 'Pesticide': 'Pesticide', 'PesticideP': 'PesticideP', 'Tox_Rel': 'Tox_Rel', 'Tox_Rel_P': 'Tox_Rel_P', 'Traffic': 'Traffic', 'TrafficP': 'TrafficP', 'DrinkWat': 'DrinkWat', 'DrinkWatP': 'DrinkWatP', 'Lead': 'Lead', 'Lead_P': 'Lead_P', 'Cleanup': 'Cleanup', 'CleanupP': 'CleanupP', 'GWThreat': 'GWThreat', 'GWThreatP': 'GWThreatP', 'HazWaste': 'HazWaste', 'HazWasteP': 'HazWasteP', 'ImpWatBod': 'ImpWatBod', 'ImpWatBodP': 'ImpWatBodP', 'SolWaste': 'SolWaste', 'SolWasteP': 'SolWasteP', 'PollBurd': 'PollBurd', 'PolBurdSc': 'PolBurdSc', 'PolBurdP': 'PolBurdP', 'Asthma': 'Asthma', 'AsthmaP': 'AsthmaP', 'LowBirtWt': 'LowBirtWt', 'LowBirWP': 'LowBirWP', 'Cardiovas': 'Cardiovas', 'CardiovasP': 'CardiovasP', 'Educatn': 'Educatn', 'EducatP': 'EducatP', 'Ling_Isol': 'Ling_Isol', 'Ling_IsolP': 'Ling_IsolP', 'Poverty': 'Poverty', 'PovertyP': 'PovertyP', 'Unempl': 'Unempl', 'UnemplP': 'UnemplP', 'HousBurd': 'HousBurd', 'HousBurdP': 'HousBurdP', 'PopChar': 'PopChar', 'PopCharSc': 'PopCharSc', 'PopCharP': 'PopCharP', 'Child_10': 'Child_10', 'Pop_10_64': 'Pop_10_64', 'Elderly65': 'Elderly65', 'Hispanic': 'Hispanic', 'White': 'White', 'AfricanAm': 'AfricanAm', 'NativeAm': 'NativeAm', 'OtherMult': 'OtherMult', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'AAPI': 'AAPI', });
lyr_CES5DACs40_3.set('fieldAliases', {'tract': 'tract', 'ZIP': 'ZIP', 'apx_loc': 'apx_loc', 'county': 'county', 'region': 'region', 'pop': 'pop', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'lead': 'lead', 'leadP': 'leadP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'drink': 'drink', 'drinkP': 'drinkP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatP': 'gwthreatP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'SmATS': 'SmATS', 'SmATSP': 'SmATSP', 'swis': 'swis', 'swisP': 'swisP', 'pollutn': 'pollutn', 'pltn_scr': 'pltn_scr', 'pollutnP': 'pollutnP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'diabetes': 'diabetes', 'diabetesP': 'diabetesP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'edu': 'edu', 'eduP': 'eduP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'PopChar': 'PopChar', 'PopCharScr': 'PopCharScr', 'PopCharP': 'PopCharP', 'PopUnd_10': 'PopUnd_10', 'Pop10_64': 'Pop10_64', 'popovr_65': 'popovr_65', 'whitepct': 'whitepct', 'hisppct': 'hisppct', 'blackpct': 'blackpct', 'nativeampc': 'nativeampc', 'asianpct': 'asianpct', 'otherpct': 'otherpct', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_CES5DACs30_4.set('fieldAliases', {'tract': 'tract', 'ZIP': 'ZIP', 'apx_loc': 'apx_loc', 'county': 'county', 'region': 'region', 'pop': 'pop', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'lead': 'lead', 'leadP': 'leadP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'drink': 'drink', 'drinkP': 'drinkP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatP': 'gwthreatP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'SmATS': 'SmATS', 'SmATSP': 'SmATSP', 'swis': 'swis', 'swisP': 'swisP', 'pollutn': 'pollutn', 'pltn_scr': 'pltn_scr', 'pollutnP': 'pollutnP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'diabetes': 'diabetes', 'diabetesP': 'diabetesP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'edu': 'edu', 'eduP': 'eduP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'PopChar': 'PopChar', 'PopCharScr': 'PopCharScr', 'PopCharP': 'PopCharP', 'PopUnd_10': 'PopUnd_10', 'Pop10_64': 'Pop10_64', 'popovr_65': 'popovr_65', 'whitepct': 'whitepct', 'hisppct': 'hisppct', 'blackpct': 'blackpct', 'nativeampc': 'nativeampc', 'asianpct': 'asianpct', 'otherpct': 'otherpct', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_CES5MTCSolution_5.set('fieldAliases', {'tract': 'tract', 'ZIP': 'ZIP', 'apx_loc': 'apx_loc', 'county': 'county', 'region': 'region', 'pop': 'pop', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'lead': 'lead', 'leadP': 'leadP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'drink': 'drink', 'drinkP': 'drinkP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatP': 'gwthreatP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'SmATS': 'SmATS', 'SmATSP': 'SmATSP', 'swis': 'swis', 'swisP': 'swisP', 'pollutn': 'pollutn', 'pltn_scr': 'pltn_scr', 'pollutnP': 'pollutnP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'diabetes': 'diabetes', 'diabetesP': 'diabetesP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'edu': 'edu', 'eduP': 'eduP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'PopChar': 'PopChar', 'PopCharScr': 'PopCharScr', 'PopCharP': 'PopCharP', 'PopUnd_10': 'PopUnd_10', 'Pop10_64': 'Pop10_64', 'popovr_65': 'popovr_65', 'whitepct': 'whitepct', 'hisppct': 'hisppct', 'blackpct': 'blackpct', 'nativeampc': 'nativeampc', 'asianpct': 'asianpct', 'otherpct': 'otherpct', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_CES5DACs_6.set('fieldAliases', {'tract': 'tract', 'ZIP': 'ZIP', 'apx_loc': 'apx_loc', 'county': 'county', 'region': 'region', 'pop': 'pop', 'CIscore': 'CIscore', 'CIscoreP': 'CIscoreP', 'ozone': 'ozone', 'ozoneP': 'ozoneP', 'pm': 'pm', 'pmP': 'pmP', 'lead': 'lead', 'leadP': 'leadP', 'diesel': 'diesel', 'dieselP': 'dieselP', 'drink': 'drink', 'drinkP': 'drinkP', 'pest': 'pest', 'pestP': 'pestP', 'RSEIhaz': 'RSEIhaz', 'RSEIhazP': 'RSEIhazP', 'traffic': 'traffic', 'trafficP': 'trafficP', 'cleanups': 'cleanups', 'cleanupsP': 'cleanupsP', 'gwthreats': 'gwthreats', 'gwthreatP': 'gwthreatP', 'haz': 'haz', 'hazP': 'hazP', 'iwb': 'iwb', 'iwbP': 'iwbP', 'SmATS': 'SmATS', 'SmATSP': 'SmATSP', 'swis': 'swis', 'swisP': 'swisP', 'pollutn': 'pollutn', 'pltn_scr': 'pltn_scr', 'pollutnP': 'pollutnP', 'asthma': 'asthma', 'asthmaP': 'asthmaP', 'cvd': 'cvd', 'cvdP': 'cvdP', 'diabetes': 'diabetes', 'diabetesP': 'diabetesP', 'lbw': 'lbw', 'lbwP': 'lbwP', 'edu': 'edu', 'eduP': 'eduP', 'housingB': 'housingB', 'housingBP': 'housingBP', 'ling': 'ling', 'lingP': 'lingP', 'pov': 'pov', 'povP': 'povP', 'unemp': 'unemp', 'unempP': 'unempP', 'PopChar': 'PopChar', 'PopCharScr': 'PopCharScr', 'PopCharP': 'PopCharP', 'PopUnd_10': 'PopUnd_10', 'Pop10_64': 'Pop10_64', 'popovr_65': 'popovr_65', 'whitepct': 'whitepct', 'hisppct': 'hisppct', 'blackpct': 'blackpct', 'nativeampc': 'nativeampc', 'asianpct': 'asianpct', 'otherpct': 'otherpct', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_CES3DACs_1.set('fieldImages', {'tract': '', 'pop2010': '', 'California': '', 'ZIP': '', 'City': '', 'Longitude': '', 'Latitude': '', 'CIscore': '', 'CIscoreP': '', 'ozone': '', 'ozoneP': '', 'pm': '', 'pmP': '', 'diesel': '', 'dieselP': '', 'drink': '', 'drinkP': '', 'pest': '', 'pestP': '', 'RSEIhaz': '', 'RSEIhazP': '', 'traffic': '', 'trafficP': '', 'cleanups': '', 'cleanupsP': '', 'gwthreats': '', 'gwthreatsP': '', 'haz': '', 'hazP': '', 'iwb': '', 'iwbP': '', 'swis': '', 'swisP': '', 'Pollution': '', 'PollutionS': '', 'PollutionP': '', 'asthma': '', 'asthmaP': '', 'lbw': '', 'lbwP': '', 'cvd': '', 'cvdP': '', 'edu': '', 'eduP': '', 'ling': '', 'lingP': '', 'pov': '', 'povP': '', 'unemp': '', 'unempP': '', 'housingB': '', 'housingBP': '', 'PopChar': '', 'PopCharSco': '', 'PopCharP': '', 'Children_u': '', 'Pop_11_64_': '', 'Elderly_ov': '', 'Hispanic_p': '', 'White_pct': '', 'African_Am': '', 'Native_Ame': '', 'Asian_Amer': '', 'Other_pct': '', 'OBJECTID_1': '', 'CIdecile': '', 'CIvigintil': '', 'Shape_Leng': '', 'Shape_Area': '', 'CES2018_Rn': '', });
lyr_CES4DACs_2.set('fieldImages', {'Tract': '', 'ZIP': '', 'County': '', 'ApproxLoc': '', 'TotPop19': '', 'CIscore': '', 'CIscoreP': '', 'Ozone': '', 'OzoneP': '', 'PM2_5': '', 'PM2_5_P': '', 'DieselPM': '', 'DieselPM_P': '', 'Pesticide': '', 'PesticideP': '', 'Tox_Rel': '', 'Tox_Rel_P': '', 'Traffic': '', 'TrafficP': '', 'DrinkWat': '', 'DrinkWatP': '', 'Lead': '', 'Lead_P': '', 'Cleanup': '', 'CleanupP': '', 'GWThreat': '', 'GWThreatP': '', 'HazWaste': '', 'HazWasteP': '', 'ImpWatBod': '', 'ImpWatBodP': '', 'SolWaste': '', 'SolWasteP': '', 'PollBurd': '', 'PolBurdSc': '', 'PolBurdP': '', 'Asthma': '', 'AsthmaP': '', 'LowBirtWt': '', 'LowBirWP': '', 'Cardiovas': '', 'CardiovasP': '', 'Educatn': '', 'EducatP': '', 'Ling_Isol': '', 'Ling_IsolP': '', 'Poverty': '', 'PovertyP': '', 'Unempl': '', 'UnemplP': '', 'HousBurd': '', 'HousBurdP': '', 'PopChar': '', 'PopCharSc': '', 'PopCharP': '', 'Child_10': '', 'Pop_10_64': '', 'Elderly65': '', 'Hispanic': '', 'White': '', 'AfricanAm': '', 'NativeAm': '', 'OtherMult': '', 'Shape_Leng': '', 'Shape_Area': '', 'AAPI': '', });
lyr_CES5DACs40_3.set('fieldImages', {'tract': '', 'ZIP': '', 'apx_loc': '', 'county': '', 'region': '', 'pop': '', 'CIscore': '', 'CIscoreP': '', 'ozone': '', 'ozoneP': '', 'pm': '', 'pmP': '', 'lead': '', 'leadP': '', 'diesel': '', 'dieselP': '', 'drink': '', 'drinkP': '', 'pest': '', 'pestP': '', 'RSEIhaz': '', 'RSEIhazP': '', 'traffic': '', 'trafficP': '', 'cleanups': '', 'cleanupsP': '', 'gwthreats': '', 'gwthreatP': '', 'haz': '', 'hazP': '', 'iwb': '', 'iwbP': '', 'SmATS': '', 'SmATSP': '', 'swis': '', 'swisP': '', 'pollutn': '', 'pltn_scr': '', 'pollutnP': '', 'asthma': '', 'asthmaP': '', 'cvd': '', 'cvdP': '', 'diabetes': '', 'diabetesP': '', 'lbw': '', 'lbwP': '', 'edu': '', 'eduP': '', 'housingB': '', 'housingBP': '', 'ling': '', 'lingP': '', 'pov': '', 'povP': '', 'unemp': '', 'unempP': '', 'PopChar': '', 'PopCharScr': '', 'PopCharP': '', 'PopUnd_10': '', 'Pop10_64': '', 'popovr_65': '', 'whitepct': '', 'hisppct': '', 'blackpct': '', 'nativeampc': '', 'asianpct': '', 'otherpct': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_CES5DACs30_4.set('fieldImages', {'tract': '', 'ZIP': '', 'apx_loc': '', 'county': '', 'region': '', 'pop': '', 'CIscore': '', 'CIscoreP': '', 'ozone': '', 'ozoneP': '', 'pm': '', 'pmP': '', 'lead': '', 'leadP': '', 'diesel': '', 'dieselP': '', 'drink': '', 'drinkP': '', 'pest': '', 'pestP': '', 'RSEIhaz': '', 'RSEIhazP': '', 'traffic': '', 'trafficP': '', 'cleanups': '', 'cleanupsP': '', 'gwthreats': '', 'gwthreatP': '', 'haz': '', 'hazP': '', 'iwb': '', 'iwbP': '', 'SmATS': '', 'SmATSP': '', 'swis': '', 'swisP': '', 'pollutn': '', 'pltn_scr': '', 'pollutnP': '', 'asthma': '', 'asthmaP': '', 'cvd': '', 'cvdP': '', 'diabetes': '', 'diabetesP': '', 'lbw': '', 'lbwP': '', 'edu': '', 'eduP': '', 'housingB': '', 'housingBP': '', 'ling': '', 'lingP': '', 'pov': '', 'povP': '', 'unemp': '', 'unempP': '', 'PopChar': '', 'PopCharScr': '', 'PopCharP': '', 'PopUnd_10': '', 'Pop10_64': '', 'popovr_65': '', 'whitepct': '', 'hisppct': '', 'blackpct': '', 'nativeampc': '', 'asianpct': '', 'otherpct': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_CES5MTCSolution_5.set('fieldImages', {'tract': 'TextEdit', 'ZIP': 'TextEdit', 'apx_loc': 'TextEdit', 'county': 'TextEdit', 'region': 'TextEdit', 'pop': 'TextEdit', 'CIscore': 'TextEdit', 'CIscoreP': 'TextEdit', 'ozone': 'TextEdit', 'ozoneP': 'TextEdit', 'pm': 'TextEdit', 'pmP': 'TextEdit', 'lead': 'TextEdit', 'leadP': 'TextEdit', 'diesel': 'TextEdit', 'dieselP': 'TextEdit', 'drink': 'TextEdit', 'drinkP': 'TextEdit', 'pest': 'TextEdit', 'pestP': 'TextEdit', 'RSEIhaz': 'TextEdit', 'RSEIhazP': 'TextEdit', 'traffic': 'TextEdit', 'trafficP': 'TextEdit', 'cleanups': 'TextEdit', 'cleanupsP': 'TextEdit', 'gwthreats': 'TextEdit', 'gwthreatP': 'TextEdit', 'haz': 'TextEdit', 'hazP': 'TextEdit', 'iwb': 'TextEdit', 'iwbP': 'TextEdit', 'SmATS': 'TextEdit', 'SmATSP': 'TextEdit', 'swis': 'TextEdit', 'swisP': 'TextEdit', 'pollutn': 'TextEdit', 'pltn_scr': 'TextEdit', 'pollutnP': 'TextEdit', 'asthma': 'TextEdit', 'asthmaP': 'TextEdit', 'cvd': 'TextEdit', 'cvdP': 'TextEdit', 'diabetes': 'TextEdit', 'diabetesP': 'TextEdit', 'lbw': 'TextEdit', 'lbwP': 'TextEdit', 'edu': 'TextEdit', 'eduP': 'TextEdit', 'housingB': 'TextEdit', 'housingBP': 'TextEdit', 'ling': 'TextEdit', 'lingP': 'TextEdit', 'pov': 'TextEdit', 'povP': 'TextEdit', 'unemp': 'TextEdit', 'unempP': 'TextEdit', 'PopChar': 'TextEdit', 'PopCharScr': 'TextEdit', 'PopCharP': 'TextEdit', 'PopUnd_10': 'TextEdit', 'Pop10_64': 'TextEdit', 'popovr_65': 'TextEdit', 'whitepct': 'TextEdit', 'hisppct': 'TextEdit', 'blackpct': 'TextEdit', 'nativeampc': 'TextEdit', 'asianpct': 'TextEdit', 'otherpct': 'TextEdit', 'Shape_Leng': 'TextEdit', 'Shape_Area': 'TextEdit', });
lyr_CES5DACs_6.set('fieldImages', {'tract': '', 'ZIP': '', 'apx_loc': '', 'county': '', 'region': '', 'pop': '', 'CIscore': '', 'CIscoreP': '', 'ozone': '', 'ozoneP': '', 'pm': '', 'pmP': '', 'lead': '', 'leadP': '', 'diesel': '', 'dieselP': '', 'drink': '', 'drinkP': '', 'pest': '', 'pestP': '', 'RSEIhaz': '', 'RSEIhazP': '', 'traffic': '', 'trafficP': '', 'cleanups': '', 'cleanupsP': '', 'gwthreats': '', 'gwthreatP': '', 'haz': '', 'hazP': '', 'iwb': '', 'iwbP': '', 'SmATS': '', 'SmATSP': '', 'swis': '', 'swisP': '', 'pollutn': '', 'pltn_scr': '', 'pollutnP': '', 'asthma': '', 'asthmaP': '', 'cvd': '', 'cvdP': '', 'diabetes': '', 'diabetesP': '', 'lbw': '', 'lbwP': '', 'edu': '', 'eduP': '', 'housingB': '', 'housingBP': '', 'ling': '', 'lingP': '', 'pov': '', 'povP': '', 'unemp': '', 'unempP': '', 'PopChar': '', 'PopCharScr': '', 'PopCharP': '', 'PopUnd_10': '', 'Pop10_64': '', 'popovr_65': '', 'whitepct': '', 'hisppct': '', 'blackpct': '', 'nativeampc': '', 'asianpct': '', 'otherpct': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_CES3DACs_1.set('fieldLabels', {'tract': 'header label - always visible', 'pop2010': 'hidden field', 'California': 'header label - always visible', 'ZIP': 'hidden field', 'City': 'hidden field', 'Longitude': 'hidden field', 'Latitude': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatsP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'Pollution': 'hidden field', 'PollutionS': 'hidden field', 'PollutionP': 'hidden field', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'PopChar': 'hidden field', 'PopCharSco': 'hidden field', 'PopCharP': 'hidden field', 'Children_u': 'hidden field', 'Pop_11_64_': 'hidden field', 'Elderly_ov': 'hidden field', 'Hispanic_p': 'hidden field', 'White_pct': 'hidden field', 'African_Am': 'hidden field', 'Native_Ame': 'hidden field', 'Asian_Amer': 'hidden field', 'Other_pct': 'hidden field', 'OBJECTID_1': 'hidden field', 'CIdecile': 'hidden field', 'CIvigintil': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', 'CES2018_Rn': 'hidden field', });
lyr_CES4DACs_2.set('fieldLabels', {'Tract': 'header label - always visible', 'ZIP': 'hidden field', 'County': 'hidden field', 'ApproxLoc': 'hidden field', 'TotPop19': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'Ozone': 'hidden field', 'OzoneP': 'hidden field', 'PM2_5': 'hidden field', 'PM2_5_P': 'hidden field', 'DieselPM': 'hidden field', 'DieselPM_P': 'hidden field', 'Pesticide': 'hidden field', 'PesticideP': 'hidden field', 'Tox_Rel': 'hidden field', 'Tox_Rel_P': 'hidden field', 'Traffic': 'hidden field', 'TrafficP': 'hidden field', 'DrinkWat': 'hidden field', 'DrinkWatP': 'hidden field', 'Lead': 'hidden field', 'Lead_P': 'hidden field', 'Cleanup': 'hidden field', 'CleanupP': 'hidden field', 'GWThreat': 'hidden field', 'GWThreatP': 'hidden field', 'HazWaste': 'hidden field', 'HazWasteP': 'hidden field', 'ImpWatBod': 'hidden field', 'ImpWatBodP': 'hidden field', 'SolWaste': 'hidden field', 'SolWasteP': 'hidden field', 'PollBurd': 'hidden field', 'PolBurdSc': 'hidden field', 'PolBurdP': 'hidden field', 'Asthma': 'hidden field', 'AsthmaP': 'hidden field', 'LowBirtWt': 'hidden field', 'LowBirWP': 'hidden field', 'Cardiovas': 'hidden field', 'CardiovasP': 'hidden field', 'Educatn': 'hidden field', 'EducatP': 'hidden field', 'Ling_Isol': 'hidden field', 'Ling_IsolP': 'hidden field', 'Poverty': 'hidden field', 'PovertyP': 'hidden field', 'Unempl': 'hidden field', 'UnemplP': 'hidden field', 'HousBurd': 'hidden field', 'HousBurdP': 'hidden field', 'PopChar': 'hidden field', 'PopCharSc': 'hidden field', 'PopCharP': 'hidden field', 'Child_10': 'hidden field', 'Pop_10_64': 'hidden field', 'Elderly65': 'hidden field', 'Hispanic': 'hidden field', 'White': 'hidden field', 'AfricanAm': 'hidden field', 'NativeAm': 'hidden field', 'OtherMult': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', 'AAPI': 'hidden field', });
lyr_CES5DACs40_3.set('fieldLabels', {'tract': 'header label - always visible', 'ZIP': 'hidden field', 'apx_loc': 'header label - always visible', 'county': 'hidden field', 'region': 'hidden field', 'pop': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'lead': 'hidden field', 'leadP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'SmATS': 'hidden field', 'SmATSP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'pollutn': 'hidden field', 'pltn_scr': 'hidden field', 'pollutnP': 'hidden field', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'diabetes': 'hidden field', 'diabetesP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'PopChar': 'hidden field', 'PopCharScr': 'hidden field', 'PopCharP': 'hidden field', 'PopUnd_10': 'hidden field', 'Pop10_64': 'hidden field', 'popovr_65': 'hidden field', 'whitepct': 'hidden field', 'hisppct': 'hidden field', 'blackpct': 'hidden field', 'nativeampc': 'hidden field', 'asianpct': 'hidden field', 'otherpct': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', });
lyr_CES5DACs30_4.set('fieldLabels', {'tract': 'header label - always visible', 'ZIP': 'hidden field', 'apx_loc': 'header label - always visible', 'county': 'hidden field', 'region': 'hidden field', 'pop': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'lead': 'hidden field', 'leadP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'SmATS': 'hidden field', 'SmATSP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'pollutn': 'hidden field', 'pltn_scr': 'hidden field', 'pollutnP': 'hidden field', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'diabetes': 'hidden field', 'diabetesP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'PopChar': 'hidden field', 'PopCharScr': 'hidden field', 'PopCharP': 'hidden field', 'PopUnd_10': 'hidden field', 'Pop10_64': 'hidden field', 'popovr_65': 'hidden field', 'whitepct': 'hidden field', 'hisppct': 'hidden field', 'blackpct': 'hidden field', 'nativeampc': 'hidden field', 'asianpct': 'hidden field', 'otherpct': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', });
lyr_CES5MTCSolution_5.set('fieldLabels', {'tract': 'header label - always visible', 'ZIP': 'hidden field', 'apx_loc': 'header label - always visible', 'county': 'hidden field', 'region': 'hidden field', 'pop': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'lead': 'hidden field', 'leadP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'SmATS': 'hidden field', 'SmATSP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'pollutn': 'hidden field', 'pltn_scr': 'hidden field', 'pollutnP': 'header label - always visible', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'diabetes': 'hidden field', 'diabetesP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'PopChar': 'hidden field', 'PopCharScr': 'hidden field', 'PopCharP': 'header label - always visible', 'PopUnd_10': 'hidden field', 'Pop10_64': 'hidden field', 'popovr_65': 'hidden field', 'whitepct': 'hidden field', 'hisppct': 'hidden field', 'blackpct': 'hidden field', 'nativeampc': 'hidden field', 'asianpct': 'hidden field', 'otherpct': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', });
lyr_CES5DACs_6.set('fieldLabels', {'tract': 'header label - always visible', 'ZIP': 'hidden field', 'apx_loc': 'header label - always visible', 'county': 'hidden field', 'region': 'hidden field', 'pop': 'hidden field', 'CIscore': 'hidden field', 'CIscoreP': 'header label - always visible', 'ozone': 'hidden field', 'ozoneP': 'hidden field', 'pm': 'hidden field', 'pmP': 'hidden field', 'lead': 'hidden field', 'leadP': 'hidden field', 'diesel': 'hidden field', 'dieselP': 'hidden field', 'drink': 'hidden field', 'drinkP': 'hidden field', 'pest': 'hidden field', 'pestP': 'hidden field', 'RSEIhaz': 'hidden field', 'RSEIhazP': 'hidden field', 'traffic': 'hidden field', 'trafficP': 'hidden field', 'cleanups': 'hidden field', 'cleanupsP': 'hidden field', 'gwthreats': 'hidden field', 'gwthreatP': 'hidden field', 'haz': 'hidden field', 'hazP': 'hidden field', 'iwb': 'hidden field', 'iwbP': 'hidden field', 'SmATS': 'hidden field', 'SmATSP': 'hidden field', 'swis': 'hidden field', 'swisP': 'hidden field', 'pollutn': 'hidden field', 'pltn_scr': 'hidden field', 'pollutnP': 'hidden field', 'asthma': 'hidden field', 'asthmaP': 'hidden field', 'cvd': 'hidden field', 'cvdP': 'hidden field', 'diabetes': 'hidden field', 'diabetesP': 'hidden field', 'lbw': 'hidden field', 'lbwP': 'hidden field', 'edu': 'hidden field', 'eduP': 'hidden field', 'housingB': 'hidden field', 'housingBP': 'hidden field', 'ling': 'hidden field', 'lingP': 'hidden field', 'pov': 'hidden field', 'povP': 'hidden field', 'unemp': 'hidden field', 'unempP': 'hidden field', 'PopChar': 'hidden field', 'PopCharScr': 'hidden field', 'PopCharP': 'hidden field', 'PopUnd_10': 'hidden field', 'Pop10_64': 'hidden field', 'popovr_65': 'hidden field', 'whitepct': 'hidden field', 'hisppct': 'hidden field', 'blackpct': 'hidden field', 'nativeampc': 'hidden field', 'asianpct': 'hidden field', 'otherpct': 'hidden field', 'Shape_Leng': 'hidden field', 'Shape_Area': 'hidden field', });
lyr_CES5DACs_6.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});